config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :statuses
  root "statuses#index"

    
    
end

app/models/status.rb
class Status < ActiveRecord::Base
    attr_accessible :contenido, :user_id
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    
    attr_accessible :primer_nombre, :primer_apellido, :nombre_perfil, :email, :encrypted_password, :email, :password, :password_confirmation
    
    has_many :statuses
    
    def nombre_completo
        primer_nombre + " " + primer_apellido
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:primer_nombre, :primer_apellido, :nombre_perfil, :email, :password, :password_confirmation)}
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
      
      respond_to do |format|
          format.html # index.html.erb
          format.json {render json: @statuses}
      end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
        params.require(:status).permit(:user_id, :contenido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ojalabook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
            <a href="#" class="navbar-brand">JavierBook</a>
            
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Status", statuses_path%></li>
            </ul>
                <ul class="nav navbar-nav pull-right">
                    <% if user_signed_in? %>
                        <li><%= link_to current_user.nombre_completo, edit_user_registration_path %></li>
                        <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
                    <%else%>
                        <li><%= link_to "Registrar", new_user_registration_path %></li>
                        <li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
                    <%end%>
                </ul>
            
        </div>
</div>

<div class="container">
       <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        
        <%= yield %>
</div>
</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status,html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
<%=f.input :user_id, collection: User.all, label_method: :nombre_completo%>  
<%=f.input :contenido%>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
    <h1>Todos los estados</h1>
</div>

<%= link_to "Crear nuevo post", new_status_path, class: "btn btn-success"%>

<% @statuses.each do |status|%>
    
    <div class="status">
        <strong><%= status.user.nombre_completo%></strong>
        <p><%= status.contenido%></p>  
        <div>
            <%= link_to "Hace "+ time_ago_in_words(status.created_at), status%>
            <span class="admin">
                <%= link_to "Editar", edit_status_path(status)%>
                <%= link_to "Borrar", status, method: :delete, data:{confirm: "¿Estas seguro que quieres eliminar este estado?"}%>
            </span>
        </div>  
    </div>
    
    
    
<%end%>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
    <%= @status.user.nombre_completo%>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @status.contenido %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>